language: python
python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9-dev"
 - "pypy"
 - "pypy3"
jobs:
 allow_failures:
  - python: "3.9-dev"
install:
 - pip install -q "flake8"
script:
 - nosetests --with-coverage --cover-package=statsd
 - flake8 statsd/
